### ISSUE TITLE
$broadcast

### ISSUE THREAD

**Issue by darrylkuhn** [callmehiphop/hey#3]
First thanks for taking the time to open source this and support it!

Is there a reason hey only supports $emit() and not also $broadcast()? I recognize that I can throw a $rootScope.$broadcast() but that requires me to inject $rootScope and that's one of the things I am trying to avoid (once it's injected then it's more likely to be abused)...

**Comment by callmehiphop** [comment]
Thanks for opening an issue!

I think my original use case didn't call for `$broadcast`, but I would more than happy to support it! Any chance you would like to submit a PR? Otherwise I can get to it soonish.

**Comment by darrylkuhn** [comment]
Cool - I'll work it up and submit a PR.
